name: Generate Score

on:
  push:
    branches: []
    
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          
      - run: npm ci
      
      - name: Setup Nu
        uses: hustcer/setup-nu@v3.9
      - name: Sanity Check
        run: ls
      - name: Run Score Script
        run: nu bin/test-score.nu
